# **ACTIVATION FUNCTIONS**

# **RELU**

Converts negative input to 0

In [1]:
import torch.nn
import torch
import numpy as np

In [2]:
relu=torch.nn.ReLU()
sample=torch.tensor([-1.0,-2.0,0,0.5000,2.000])
act=relu(sample)
sample,act

(tensor([-1.0000, -2.0000,  0.0000,  0.5000,  2.0000]),
 tensor([0.0000, 0.0000, 0.0000, 0.5000, 2.0000]))

# **GELU**

A smoother gently curving version of RELu

In [3]:
gelu=torch.nn.GELU()
act=gelu(sample)
sample,act

(tensor([-1.0000, -2.0000,  0.0000,  0.5000,  2.0000]),
 tensor([-0.1587, -0.0455,  0.0000,  0.3457,  1.9545]))

# **SOFTMAX**

Converts logits to pdf

In [4]:
softmax=torch.nn.Softmax(dim=-1)
logits=torch.tensor([[1.0,3.5,7,9,2.0],[1.5,2.3,4.5,2.1,0.1]])
act=softmax(logits)
logits,act

(tensor([[1.0000, 3.5000, 7.0000, 9.0000, 2.0000],
         [1.5000, 2.3000, 4.5000, 2.1000, 0.1000]]),
 tensor([[2.9409e-04, 3.5828e-03, 1.1865e-01, 8.7668e-01, 7.9943e-04],
         [3.9401e-02, 8.7689e-02, 7.9140e-01, 7.1794e-02, 9.7163e-03]]))

# **LAYERNORM**

Prevents values from exploding or vanishing (x-mean)/std

In [5]:
norm_layer=torch.nn.LayerNorm(normalized_shape=3)
input_features=torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]])
output_features=norm_layer(input_features)
input_features,output_features

(tensor([[1., 2., 3.],
         [4., 5., 6.]]),
 tensor([[-1.2247,  0.0000,  1.2247],
         [-1.2247,  0.0000,  1.2247]], grad_fn=<NativeLayerNormBackward0>))

# **DROPOUT**

Randomly zeros out neuron while training prevents overfitting

In [6]:
dropout_layer=torch.nn.Dropout(p=0.5)
input_tensor=torch.ones(1,10)
dropout_layer.train()
output_tensor=dropout_layer(input_tensor)
input_tensor,output_tensor
dropout_layer.eval()
output_tensor=dropout_layer(input_tensor)
input_tensor,output_tensor

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))