# **LINEAR REGRESSION MANUAL**

In [39]:
"""
Topic: Linear Regression (Manual)

What this file shows:
- Manual gradient descent
- MSE loss
- Parameter updates
"""

'\nTopic: Linear Regression (Manual)\n\nWhat this file shows:\n- Manual gradient descent\n- MSE loss\n- Parameter updates\n'

# **IMPORTS + DATA**

In [40]:
import numpy as np
import torch

In [41]:
inputs=np.array([[73.,67,45],[91,88,64],[87,134,58],[102,43,37],[69,96,70]])

In [42]:
inputs

array([[ 73.,  67.,  45.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]])

In [43]:
target=np.array([[56.,70],[81,101],[119,113],[22,37],[103,119]])

In [44]:
target

array([[ 56.,  70.],
       [ 81., 101.],
       [119., 113.],
       [ 22.,  37.],
       [103., 119.]])

In [45]:
inputs = torch.from_numpy(inputs).to(torch.float32)
inputs
target = torch.from_numpy(target).to(torch.float32)
target

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 113.],
        [ 22.,  37.],
        [103., 119.]])

# **MODEL AND LOSS**

In [46]:
#MODEL PARAMETERS

In [47]:
w=torch.randn(2,3,requires_grad=True)
b=torch.randn(2,requires_grad=True)
print(w)
print(b)

tensor([[-0.0234,  0.6884, -0.1209],
        [ 0.8310,  0.2171, -0.4039]], requires_grad=True)
tensor([ 0.1949, -0.4875], requires_grad=True)


In [48]:
def model(x):
  return x@ w.t() +b

In [49]:
inputs.float() @ w.t() +b

tensor([[39.1689, 56.5468],
        [50.9073, 68.3901],
        [83.3940, 77.4739],
        [22.9335, 78.6681],
        [56.2054, 49.4208]], grad_fn=<AddBackward0>)

In [50]:
def mse(t1,t2):
  diff=t1-t2
  return torch.sum(diff*diff)/diff.numel()

# **FORWARD AND BACKWARD PASS**

In [51]:
preds=model(inputs.float())
preds

tensor([[39.1689, 56.5468],
        [50.9073, 68.3901],
        [83.3940, 77.4739],
        [22.9335, 78.6681],
        [56.2054, 49.4208]], grad_fn=<AddBackward0>)

In [52]:
diff=preds-target
diff

tensor([[-16.8311, -13.4532],
        [-30.0927, -32.6099],
        [-35.6060, -35.5261],
        [  0.9335,  41.6681],
        [-46.7946, -69.5792]], grad_fn=<SubBackward0>)

In [53]:
mse(preds,target)

tensor(1373.1254, grad_fn=<DivBackward0>)

In [54]:
loss=mse(preds,target)

In [55]:
loss.backward()

In [56]:
print(w.grad)

tensor([[-2039.6884, -2599.8386, -1597.9135],
        [-1518.2346, -2683.8823, -1616.3533]])


In [57]:
print(loss)

tensor(1373.1254, grad_fn=<DivBackward0>)


In [58]:
print(b.grad)

tensor([-25.6782, -21.9001])


In [59]:
pred=model(inputs.float())

In [60]:
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5

In [61]:
loss=mse(preds,target)

In [62]:
loss

tensor(1373.1254, grad_fn=<DivBackward0>)

# **TRAINING LOOP**

In [63]:

learning_rate = 1e-5
epochs = 100

for epoch in range(epochs):
    preds = model(inputs)
    loss = mse(preds, target)

    loss.backward()

    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad

        w.grad.zero_()
        b.grad.zero_()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")

Epoch 0, Loss: 1139.5747
Epoch 10, Loss: 609.6245
Epoch 20, Loss: 551.3800
Epoch 30, Loss: 503.8128
Epoch 40, Loss: 461.6607
Epoch 50, Loss: 424.2078
Epoch 60, Loss: 390.8981
Epoch 70, Loss: 361.2438
Epoch 80, Loss: 334.8148
Epoch 90, Loss: 311.2320
