# **INTRODUCTION TO TENSORS TUTORIAL**

# **TENSOR BASICS**

In [25]:
import torch

In [26]:
t1=torch.tensor(4.)
t1

tensor(4.)

In [27]:
t2=torch.tensor([1.,2,3,4,5])
t2

tensor([1., 2., 3., 4., 5.])

In [28]:
t3=torch.tensor([[1,2,3],[4,5,6]])

In [29]:
t4=torch.tensor([[[1,2],[3,4]],[[5,6],[7,8]]])

In [30]:
t1.shape

torch.Size([])

In [31]:
t2.shape

torch.Size([5])

In [32]:
t3.shape

torch.Size([2, 3])

In [33]:
t4.shape

torch.Size([2, 2, 2])

# **AUTOGRAD EXAMPLE**

In [34]:
x=torch.tensor(4.,requires_grad=True)
w=torch.tensor(5.,requires_grad=True)
b=torch.tensor(6.,requires_grad=True  )
x,w,b

(tensor(4., requires_grad=True),
 tensor(5., requires_grad=True),
 tensor(6., requires_grad=True))

In [35]:
y=w*x+b
y

tensor(26., grad_fn=<AddBackward0>)

In [36]:
y.backward()

In [37]:
#Reset gradients

In [38]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx tensor(5.)
dy/dw tensor(4.)
dy/db tensor(1.)


In [39]:
#Another function

In [40]:
z=(w**2)*x+b*w

In [41]:
z.backward()

In [42]:
#Reset gradients

In [43]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)

dy/dx tensor(30.)
dy/dw tensor(50.)
dy/db tensor(6.)


# **TENSOR OPERATIONS**

In [44]:
t4=torch.full((2,3),42)
t4

tensor([[42, 42, 42],
        [42, 42, 42]])

In [45]:
t5=torch.cat((t3,t4))
t5

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [42, 42, 42],
        [42, 42, 42]])

In [46]:
t8=torch.sin(t5)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])

In [47]:
t9=t8.reshape(2,2,3)
t9

tensor([[[ 0.8415,  0.9093,  0.1411],
         [-0.7568, -0.9589, -0.2794]],

        [[-0.9165, -0.9165, -0.9165],
         [-0.9165, -0.9165, -0.9165]]])

# **Numpy and tensor**

In [48]:
import numpy as  np

In [49]:
c=np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [50]:
d=torch.from_numpy(c)
d

tensor([[1, 2],
        [3, 4]])

In [51]:
c.dtype,d.dtype

(dtype('int64'), torch.int64)